export const sourceLayout = [
  "src/core/bootstrap.js",
  "src/ui/dialog-accessibility.js",
  "src/config/definitions.js",
  "src/api/platform.js",
  "src/ui/navigator-shell.js",
  "src/features/betty5/settings.js",
  "src/features/betty5/action-highlighting.js",
  "src/features/betty5/password-revealer.js",
  "src/features/betty5/variable-search.js",
  "src/features/ui-builder/mask-setting.js",
  "src/features/nextgen/action-playground/context.js",
  "src/features/nextgen/action-playground/validation.js",
  "src/features/nextgen/action-playground/ui.js",
  "src/features/nextgen/action-type-icons.js",
  "src/features/nextgen/duplicate-action-step.js",
  "src/features/nextgen/action-step-history.js",
  "src/features/nextgen/log-downloader.js",
  "src/ui/settings/changes.js",
  "src/ui/settings/info.js",
  "src/ui/settings/data.js",
  "src/ui/settings/navigation.js",
  "src/ui/settings/dialog.js",
  "src/features/navigation-tools.js",
  "src/features/artifact-explorer.js",
  "src/features/release-updates.js",
  "src/features/product-education.js",
  "src/features/command-palette.js",
  "src/ui/navigator-config.js",
  "src/main.js",
];

export const outputFile = "dist/bb-powerbrowser.user.js";
